k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 60d4dfe5-f172-5314-862c-b9cb10f5f5e9
    cluster_name: Patrick Lamprecht's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: eee4e8dd-7962-50fb-981c-5a530468105f
    cluster_name: Patrick Lamprecht's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 60d4dfe5-f172-5314-862c-b9cb10f5f5e9
    cluster_name: Patrick Lamprecht's cluster
