apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 378d0e71-d0b0-4169-a58f-bae85ce28b91
  creationTimestamp: null
  name: rollout-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    canary:
      canaryService: rollout-demo-canary
      stableService: rollout-demo
      steps:
      - setWeight: 50
      - pause:
          duration: 10
      - setWeight: 100
      - pause:
          duration: 10
      trafficRouting:
        ambassador:
          mappings:
          - rollout-demo-mapping
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - image: traefik/whoami:v1.8
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 80
        resources: {}
status:
  blueGreen: {}
  canary: {}
